### ISSUE TITLE
Using version 1.5.0 results in error on initialisation

### ISSUE THREAD

**Issue by tveimo** [asual/lesscss-servlet#23]
lesscss.LessEngine.<init>() - line 118 [] - LESS Engine intialization failed.
org.mozilla.javascript.EvaluatorException: illegal character (/Users/torgeir/java/apache-tomcat-7.0.47/work/Catalina/localhost/frontend/loader/META-INF/less.js#2588)
    at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:109)
    at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:96)
...

**Comment by tveimo** [comment]
Looks like there's an error in line 2588 of less.js. It reads 

```
    ('file://' + ctx.debugInfo.fileName).replace(/([.:/\\])/g, function (a) {
```

in the most recent version of less.js, it's 

```
    ('file://' + ctx.debugInfo.fileName).replace(/([.:\/\\])/g, function (a) {
```

ie, the / behind the colon is escaped like \/ (in lib/less/tree.js). It's related to this issue;

https://github.com/less/less.js/commit/15af82848d6417f3578470257faed43f61c22331

Any chance we can get a fixed version in maven?
